# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dr2zo6AT4LJH5O8CRXcyfaJaYmV4Dc0F
"""

import streamlit as st
import os
import tempfile
import librosa
import numpy as np
import scipy.signal
import soundfile as sf
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, ConfusionMatrixDisplay

# --- UI Setup ---
st.set_page_config(page_title="HW3 Audio ML App", layout="wide")
st.title("🎧 Audio Classification App")
st.write("Upload your training data (HW3) and unseen test data (HW2). The app will process the audio, train the model, and evaluate performance across all sets.")

# --- HW3 Functions ---
def split_and_save_hits(input_file, output_folder, top_db=25, min_hit_duration=0.05):
    base_name = os.path.basename(input_file).split('.')[0]
    y, sr = librosa.load(input_file, sr=None)
    intervals = librosa.effects.split(y, top_db=top_db)

    saved_count = 0
    for start, end in intervals:
        duration = (end - start) / sr
        if duration >= min_hit_duration:
            pad = int(0.02 * sr)
            start_pad = max(0, start - pad)
            end_pad = min(len(y), end + pad)

            output_path = os.path.join(output_folder, f"{base_name}_hit{saved_count+1}.wav")
            sf.write(output_path, y[start_pad:end_pad], sr)
            saved_count += 1
    return saved_count

def extract_mece_features(file_path):
    y, sr = librosa.load(file_path, sr=None)
    mfccs = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)
    mfcc_mean = np.mean(mfccs.T, axis=0)
    freqs, psd = scipy.signal.welch(y, sr)
    psd_mean = np.mean(psd)
    return np.hstack([mfcc_mean, psd_mean])

def create_dataset(folder_path):
    files = sorted([f for f in os.listdir(folder_path) if f.endswith('.wav')])
    X, y = [], []
    for f in files:
        path = os.path.join(folder_path, f)
        X.append(extract_mece_features(path))
        name_parts = f.lower().replace('.wav', '').split('_')
        if 'b' in name_parts:
            y.append(1) # Unhealthy
        else:
            y.append(0) # Healthy
    return np.array(X), np.array(y)

# --- Helper Function for File Saving ---
def save_uploaded_files(uploaded_files, target_dir):
    for uf in uploaded_files:
        with open(os.path.join(target_dir, uf.name), "wb") as f:
            f.write(uf.getbuffer())

# --- App Logic ---
model_choice = st.selectbox("Select Machine Learning Model", ["KNN (K=3)", "Decision Tree", "Logistic Regression", "SVM"])

st.write("---")
col_upload1, col_upload2 = st.columns(2)

with col_upload1:
    st.subheader("1. Training Data")
    train_files = st.file_uploader("Upload Training Data (e.g., HW3 files)", type=["wav"], accept_multiple_files=True, key="train")

with col_upload2:
    st.subheader("2. Unseen Test Data")
    test_files = st.file_uploader("Upload Unseen Data (e.g., HW2 files)", type=["wav"], accept_multiple_files=True, key="test")

if train_files and test_files:
    if st.button("Run Full ML Pipeline", type="primary"):
        st.write("---")

        # Open temporary directories for all data
        with tempfile.TemporaryDirectory() as train_raw, tempfile.TemporaryDirectory() as train_proc, \
             tempfile.TemporaryDirectory() as test_raw, tempfile.TemporaryDirectory() as test_proc:

            save_uploaded_files(train_files, train_raw)
            save_uploaded_files(test_files, test_raw)

            # --- Step A: Process Training Data ---
            st.write("### ⚙️ Processing Training Data...")
            train_bar = st.progress(0)
            train_files_list = os.listdir(train_raw)
            for index, file in enumerate(train_files_list):
                split_and_save_hits(os.path.join(train_raw, file), train_proc)
                train_bar.progress((index + 1) / len(train_files_list))

            with st.spinner('Extracting features from Training Data...'):
                X_train_full, y_train_full = create_dataset(train_proc)

            # --- Step B: Process Unseen Test Data ---
            st.write("### ⚙️ Processing Unseen Test Data...")
            test_bar = st.progress(0)
            test_files_list = os.listdir(test_raw)
            for index, file in enumerate(test_files_list):
                split_and_save_hits(os.path.join(test_raw, file), test_proc)
                test_bar.progress((index + 1) / len(test_files_list))

            with st.spinner('Extracting features from Test Data...'):
                X_unseen, y_unseen = create_dataset(test_proc)

            if len(X_train_full) == 0 or len(X_unseen) == 0:
                st.error("Missing audio features. Please check the uploaded files.")
            else:
                st.success("All data processed successfully!")

                # --- Step C: Model Training & Evaluation ---
                # Split Training Data into Train (70%) and Validation (30%)
                X_train, X_val, y_train, y_val = train_test_split(
                    X_train_full, y_train_full, test_size=0.3, random_state=42, stratify=y_train_full
                )

                # Scale Data
                scaler = StandardScaler()
                X_train_scaled = scaler.fit_transform(X_train)
                X_val_scaled = scaler.transform(X_val)
                X_unseen_scaled = scaler.transform(X_unseen)

                # Setup model data based on selection
                if model_choice == "Decision Tree":
                    model = DecisionTreeClassifier(random_state=42)
                    t_data, v_data, u_data = X_train, X_val, X_unseen
                else:
                    t_data, v_data, u_data = X_train_scaled, X_val_scaled, X_unseen_scaled
                    if model_choice == "KNN (K=3)": model = KNeighborsClassifier(n_neighbors=3)
                    elif model_choice == "Logistic Regression": model = LogisticRegression(random_state=42, max_iter=1000)
                    else: model = SVC(random_state=42)

                # Train
                model.fit(t_data, y_train)

                # Predict Accuracies
                acc_train = accuracy_score(y_train, model.predict(t_data))
                acc_val = accuracy_score(y_val, model.predict(v_data))
                acc_unseen = accuracy_score(y_unseen, model.predict(u_data))

                # --- Step D: Display Results ---
                st.write("---")
                st.write(f"## 📊 Results: {model_choice}")

                # Display Metrics
                m1, m2, m3 = st.columns(3)
                m1.metric("Training Accuracy", f"{acc_train:.2%}")
                m2.metric("Validation Accuracy", f"{acc_val:.2%}")
                m3.metric("Unseen Test Accuracy", f"{acc_unseen:.2%}")

                # Display Confusion Matrices
                st.write("### Confusion Matrices")
                c1, c2, c3 = st.columns(3)

                with c1:
                    st.write("**Training Data**")
                    fig1, ax1 = plt.subplots(figsize=(4, 4))
                    ConfusionMatrixDisplay.from_estimator(model, t_data, y_train, ax=ax1, cmap='Blues')
                    st.pyplot(fig1)

                with c2:
                    st.write("**Validation Data**")
                    fig2, ax2 = plt.subplots(figsize=(4, 4))
                    ConfusionMatrixDisplay.from_estimator(model, v_data, y_val, ax=ax2, cmap='Greens')
                    st.pyplot(fig2)

                with c3:
                    st.write("**Unseen Test Data**")
                    fig3, ax3 = plt.subplots(figsize=(4, 4))
                    ConfusionMatrixDisplay.from_estimator(model, u_data, y_unseen, ax=ax3, cmap='Oranges')
                    st.pyplot(fig3)